### ISSUE TITLE
中間発表の項目で、表番号のみが書かれている

### ISSUE THREAD

**Issue by yanchof** [BeatTheDealerProject/FinalReport2018#35]
表番号のみの箇所があるので、表<数字>という形に修正

**Comment by nassu334** [comment]
申し訳ないんだけど、場所を教えてほしい

**Comment by yanchof** [comment]
現在のmasterのファイルで変換した結果の48ページ。
中間発表のセクションの評価点数の集計の部分。
一行目は「分布は表は」となっていて修正が必要。
表の後の文章で表番号のみが表示されてる
